import { StyleSheet } from 'react-native';
import { palette } from '@/src/styles/tokens';

export const modalStyles = StyleSheet.create<Record<string, any>>({
  overlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.4)', justifyContent: 'center', alignItems: 'center' },
  content: { width: '90%', maxWidth: 420, backgroundColor: palette.white, padding: 20, borderRadius: 12 },
  btn: { backgroundColor: '#64748b', padding: 10, borderRadius: 8, alignItems: 'center', marginRight: 8 },
});

export const styles = StyleSheet.create<Record<string, any>>({
  page: { paddingVertical: 32, alignItems: 'center', paddingBottom: 120 },
  container: { maxWidth: 1200, width: '100%', paddingHorizontal: 20 },
  center: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  headerCard: {
    backgroundColor: '#ffffff', borderRadius: 20, padding: 32, marginBottom: 20, alignItems: 'center', shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.1, shadowRadius: 12, elevation: 5,
  },
  headerLabel: { fontSize: 14, color: '#6b7280', fontWeight: '500', marginBottom: 8, textTransform: 'uppercase', letterSpacing: 1 },
  codigo: { fontSize: 48, fontWeight: 'bold', letterSpacing: 8, color: '#10b981', marginBottom: 16 },
  estadoBadge: { backgroundColor: '#10b981', paddingHorizontal: 24, paddingVertical: 8, borderRadius: 20 },
  estadoBadgeClosed: { backgroundColor: '#ef4444' },
  estadoBadgeText: { color: '#ffffff', fontWeight: 'bold', fontSize: 14, textTransform: 'uppercase' },
  systemStatusCard: { backgroundColor: '#1f2937', borderRadius: 16, padding: 24, marginBottom: 20 },
  systemStatusHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 12 },
  systemStatusIcon: { fontSize: 24, marginRight: 8 },
  systemStatusTitle: { color: '#ffffff', fontSize: 14, fontWeight: '600', letterSpacing: 1 },
  systemStatusValue: { color: palette.primary, fontSize: 20, fontWeight: 'bold' },
  closeNowBtn: { backgroundColor: palette.danger, padding: 12, borderRadius: 10, marginTop: 12, alignItems: 'center' },
  closeNowBtnText: { color: palette.white, fontWeight: '600' },
  statsGrid: { flexDirection: 'row', gap: 16, marginBottom: 20 },
  statCard: { flex: 1, backgroundColor: '#ffffff', borderRadius: 16, padding: 24, alignItems: 'center', shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.08, shadowRadius: 8, elevation: 3 },
  statIcon: { fontSize: 32, marginBottom: 8 },
  statNumber: { fontSize: 40, fontWeight: 'bold', color: '#111827', marginBottom: 4 },
  statLabel: { fontSize: 14, color: '#6b7280', fontWeight: '500' },
  statusCard: { backgroundColor: '#ffffff', borderRadius: 16, padding: 24, marginBottom: 20, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.08, shadowRadius: 8, elevation: 3 },
  statusTitle: { fontSize: 16, fontWeight: '600', color: '#111827', marginBottom: 8 },
  statusValue: { fontSize: 24, fontWeight: 'bold', marginBottom: 16 },
  quorumAlert: { backgroundColor: '#fef3c7', padding: 16, borderRadius: 12, flexDirection: 'row', alignItems: 'center', borderLeftWidth: 4, borderLeftColor: '#f59e0b' },
  quorumAlertIcon: { fontSize: 24, marginRight: 12 },
  quorumAlertText: { flex: 1, color: '#92400e', fontSize: 14, lineHeight: 20 },
  debateBtn: { backgroundColor: '#f59e0b', padding: 20, borderRadius: 16, alignItems: 'center', marginBottom: 24, shadowColor: '#f59e0b', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.3, shadowRadius: 8, elevation: 5 },
  debateBtnDisabled: { backgroundColor: '#d1d5db', opacity: 0.6 },
  debateBtnText: { color: palette.white, fontSize: 18, fontWeight: 'bold' },
  managementConsole: { marginBottom: 32 },
  consoleTitle: { fontSize: 18, fontWeight: 'bold', color: '#111827', marginBottom: 16 },
  actionGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
  actionCard: { width: '48%', borderRadius: 14, padding: 16, alignItems: 'center', justifyContent: 'center', minHeight: 100, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.15, shadowRadius: 6, elevation: 4 },
  actionCardIcon: { fontSize: 28, marginBottom: 6 },
  actionCardText: { color: '#ffffff', fontSize: 12, fontWeight: '600', textAlign: 'center' },
  closeAssemblyBtn: { backgroundColor: palette.danger, padding: 18, borderRadius: 16, alignItems: 'center', marginTop: 24, shadowColor: palette.danger, shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.3, shadowRadius: 8, elevation: 5 },
  closeAssemblyBtnText: { color: palette.white, fontSize: 18, fontWeight: 'bold' },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0, 0, 0, 0.6)', justifyContent: 'center', alignItems: 'center', padding: 20 },
  confirmModalContent: { backgroundColor: '#ffffff', borderRadius: 20, padding: 24, width: '100%', maxWidth: 420, shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.3, shadowRadius: 8, elevation: 8 },
  confirmModalHeader: { alignItems: 'center', marginBottom: 16 },
  confirmModalIcon: { fontSize: 56, marginBottom: 8 },
  confirmModalTitle: { fontSize: 24, fontWeight: '700', color: '#1f2937', textAlign: 'center' },
  confirmModalMessage: { fontSize: 16, color: '#6b7280', textAlign: 'center', lineHeight: 24, marginBottom: 20 },
  confirmModalStats: { backgroundColor: '#f9fafb', borderRadius: 12, padding: 16, marginBottom: 16, gap: 12 },
  statItem: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  statItemLabel: { fontSize: 14, color: '#6b7280', fontWeight: '500' },
  confirmStatValue: { fontSize: 20, fontWeight: '700', color: '#16a34a' },
  confirmModalWarning: { fontSize: 14, color: '#dc2626', textAlign: 'center', fontWeight: '600', marginBottom: 24 },
  confirmModalButtons: { flexDirection: 'row', gap: 12 },
  confirmCancelButton: { flex: 1, backgroundColor: '#f3f4f6', paddingVertical: 14, borderRadius: 12, alignItems: 'center', borderWidth: 2, borderColor: '#e5e7eb' },
  confirmCancelButtonText: { color: '#4b5563', fontSize: 16, fontWeight: '600' },
  confirmDeleteButton: { flex: 1, backgroundColor: '#dc2626', paddingVertical: 14, borderRadius: 12, alignItems: 'center', shadowColor: '#dc2626', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.3, shadowRadius: 4, elevation: 4 },
  confirmDeleteButtonDisabled: { backgroundColor: '#fca5a5', opacity: 0.7 },
  confirmDeleteButtonText: { color: '#ffffff', fontSize: 16, fontWeight: '700' },
  codigoModalContent: { backgroundColor: '#ffffff', borderRadius: 20, padding: 40, width: '100%', maxWidth: 450, alignItems: 'center', shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.3, shadowRadius: 8, elevation: 8 },
  codigoModalTitle: { fontSize: 22, fontWeight: '600', color: '#000000', marginBottom: 24, textAlign: 'center' },
  codigoModalCodigo: { fontSize: 72, fontWeight: 'bold', color: '#000000', letterSpacing: 12, marginBottom: 32, textAlign: 'center' },
  codigoModalButton: { backgroundColor: '#16a34a', paddingVertical: 14, paddingHorizontal: 40, borderRadius: 12, alignItems: 'center', minWidth: 150 },
  codigoModalButtonText: { color: '#ffffff', fontSize: 16, fontWeight: '600' },
  pageDesktop: { paddingVertical: 48, minHeight: '100%' },
  containerDesktop: { maxWidth: 1200, width: '95%', paddingHorizontal: 140 },
  headerCardDesktop: { padding: 48, marginBottom: 32 },
  codigoDesktop: { fontSize: 56, letterSpacing: 10, marginBottom: 24 },
  estadoBadgeDesktop: { paddingHorizontal: 32, paddingVertical: 12 },
  estadoBadgeTextDesktop: { fontSize: 18 },
  systemStatusCardDesktop: { padding: 32, marginBottom: 32 },
  systemStatusValueDesktop: { fontSize: 24 },
  statsGridDesktop: { gap: 24, marginBottom: 32 },
  statCardDesktop: { padding: 32 },
  statIconDesktop: { fontSize: 36, marginBottom: 12 },
  statNumberDesktop: { fontSize: 44 },
  statLabelDesktop: { fontSize: 18 },
  statusCardDesktop: { padding: 32, marginBottom: 32 },
  statusTitleDesktop: { fontSize: 20 },
  statusValueDesktop: { fontSize: 24 },
  debateBtnDesktop: { padding: 24, marginBottom: 32 },
  debateBtnTextDesktop: { fontSize: 22 },
  consoleTitleDesktop: { fontSize: 22, marginBottom: 24 },
  actionGridDesktop: { gap: 20 },
  actionCardDesktop: { minWidth: '31%', width: 'auto', padding: 28, minHeight: 120 },
  actionCardIconDesktop: { fontSize: 36 },
  actionCardTextDesktop: { fontSize: 16 },
  closeAssemblyBtnDesktop: { padding: 24 },
  closeAssemblyBtnTextDesktop: { fontSize: 22 },
});
