import { StyleSheet } from 'react-native';
import { palette } from '@/src/styles/tokens';

export const styles = StyleSheet.create({
  page: { flex: 1, alignItems: 'center' },
  container: { width: '100%', maxWidth: 700, padding: 16 },
  containerTablet: { maxWidth: 960, paddingHorizontal: 24 },
  containerDesktop: { maxWidth: '100%', paddingHorizontal: 36, paddingBottom: 24 },
  scrollContent: {
    paddingVertical: 20,
  },
  scrollContentTablet: {
    paddingVertical: 28,
  },
  scrollContentDesktop: {
    paddingVertical: 36,
    flexGrow: 1,
  },
  title: { fontSize: 26, fontWeight: '800', marginBottom: 24, color: palette.textPrimary, textAlign: 'center' },
  titleTablet: { fontSize: 32, marginBottom: 28 },
  titleDesktop: { fontSize: 44, marginBottom: 36 },
  titleProjector: { fontSize: 58, marginBottom: 16 },
  backButton: {
    backgroundColor: 'transparent',
    paddingVertical: 6,
    paddingHorizontal: 0,
    marginBottom: 16,
    alignSelf: 'flex-start',
  },
  backButtonText: {
    color: palette.primaryDark,
    fontWeight: '600',
    fontSize: 14,
  },
  backButtonTextDesktop: {
    fontSize: 18,
  },
  emptyBox: {
    backgroundColor: '#fff',
    padding: 40,
    borderRadius: 16,
    marginTop: 20,
    alignItems: 'center',
    width: '100%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  emptyIcon: { fontSize: 56, marginBottom: 12 },
  emptyText: { color: '#374151', fontSize: 18, fontWeight: '600', marginBottom: 4 },
  emptySubtext: { color: '#9ca3af', fontSize: 14 },
  card: {
    backgroundColor: '#fff',
    padding: 20,
    borderRadius: 16,
    width: '100%',
    maxWidth: 650,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.12,
    shadowRadius: 6,
    elevation: 3,
  },
  cardDesktop: {
    maxWidth: 980,
    padding: 28,
    borderRadius: 20,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  orderBadge: {
    backgroundColor: '#f3f4f6',
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
  },
  orderBadgeText: {
    color: '#6b7280',
    fontWeight: '700',
    fontSize: 14,
  },
  statusBadge: {
    backgroundColor: '#fee2e2',
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
  },
  statusBadgeText: {
    color: '#991b1b',
    fontWeight: '600',
    fontSize: 13,
  },
  cardTitle: { fontSize: 20, fontWeight: '700', marginBottom: 8, color: '#1f2937' },
  cardText: { color: '#4b5563', marginBottom: 12, fontSize: 15, lineHeight: 22 },
  cardBody: { marginBottom: 16 },
  cardActions: { flexDirection: 'row', gap: 10, justifyContent: 'flex-end' },
  cardActionsMobile: { flexDirection: 'column', alignItems: 'stretch' },
  actionBtnMobile: { width: '100%', alignItems: 'center' },
  actionBtnTextDesktop: { fontSize: 18 },
  statsBtn: {
    backgroundColor: '#f3f4f6',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#e5e7eb',
  },
  statsBtnText: { color: palette.textSecondary, fontWeight: '600', fontSize: 14 },
  publishBtn: {
    backgroundColor: palette.primary,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 10,
    shadowColor: '#16a34a',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  publishBtnText: { color: palette.white, fontWeight: '700', fontSize: 14 },
  propuestaBox: {
    width: '100%',
    backgroundColor: '#f9fafb',
    padding: 16,
    borderRadius: 12,
    marginBottom: 20,
  },
  propuestaBoxDesktop: {
    padding: 24,
    borderRadius: 16,
    marginBottom: 26,
  },
  propuestaTitulo: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1f2937',
    marginBottom: 8,
    textAlign: 'center',
  },
  propuestaTituloDesktop: {
    fontSize: 32,
    marginBottom: 12,
  },
  propuestaDescripcion: {
    fontSize: 14,
    color: '#6b7280',
    textAlign: 'center',
    lineHeight: 20,
  },
  propuestaDescripcionDesktop: {
    fontSize: 19,
    lineHeight: 28,
  },
  summaryBox: {
    width: '100%',
    backgroundColor: '#f0fdf4',
    padding: 16,
    borderRadius: 12,
    marginBottom: 24,
    gap: 8,
  },
  summaryBoxDesktop: {
    padding: 24,
    borderRadius: 16,
    marginBottom: 28,
    gap: 14,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  summaryLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#4b5563',
  },
  summaryLabelDesktop: {
    fontSize: 20,
  },
  summaryValue: {
    fontSize: 16,
    fontWeight: '700',
    color: palette.primary,
  },
  summaryValueDesktop: {
    fontSize: 28,
  },
  chartContainer: {
    width: '100%',
    backgroundColor: '#ffffff',
    borderRadius: 20,
    padding: 32,
    marginBottom: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 5,
  },
  chartTitle: {
    fontSize: 24,
    fontWeight: '800',
    color: '#1f2937',
    marginBottom: 24,
    textAlign: 'center',
  },
  columnsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'flex-end',
    height: 180,
    gap: 12,
    paddingHorizontal: 8,
    marginBottom: 16,
  },
  baseLine: {
    width: '100%',
    height: 3,
    backgroundColor: '#e5e7eb',
    borderRadius: 2,
    marginTop: -3,
  },
  columnWrapper: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-end',
    minHeight: 240,
    maxWidth: 85,
  },
  columnBar: {
    width: '100%',
    height: 100,
    backgroundColor: '#f3f4f6',
    borderRadius: 10,
    justifyContent: 'flex-end',
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: '#e5e7eb',
  },
  columnFill: {
    width: '100%',
    borderRadius: 8,
    minHeight: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
  },
  columnFillSi: { backgroundColor: palette.primary },
  columnFillNo: { backgroundColor: palette.danger },
  columnFillPending: { backgroundColor: '#f59e0b' },
  columnFillAbsent: { backgroundColor: '#9ca3af' },
  columnStats: { marginTop: 14, alignItems: 'center', height: 50 },
  columnValue: { fontSize: 24, fontWeight: '900', color: '#1f2937' },
  columnPercentage: { fontSize: 13, fontWeight: '700', color: '#6b7280' },
  columnLabelContainer: { marginTop: 4, alignItems: 'center', height: 46, justifyContent: 'flex-start' },
  columnLabel: { fontSize: 10, fontWeight: '700', color: '#4b5563', textAlign: 'center', lineHeight: 12 },
  resultBox: {
    width: '100%',
    backgroundColor: '#f0fdf4',
    padding: 20,
    borderRadius: 12,
    marginBottom: 24,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: palette.primary,
  },
  resultBoxDesktop: {
    padding: 28,
    borderRadius: 16,
    marginBottom: 32,
  },
  resultLabel: { fontSize: 16, fontWeight: '600', color: '#6b7280', marginBottom: 4 },
  resultLabelDesktop: { fontSize: 24, marginBottom: 8 },
  resultInfo: { fontSize: 14, color: '#6b7280', marginBottom: 8, textAlign: 'center' },
  resultInfoDesktop: { fontSize: 19, marginBottom: 14 },
  resultText: { fontSize: 28, fontWeight: '800', textAlign: 'center' },
  resultTextDesktop: { fontSize: 52 },
  liveBadge: {
    alignSelf: 'center',
    backgroundColor: '#fee2e2',
    borderWidth: 1,
    borderColor: '#dc2626',
    borderRadius: 999,
    paddingVertical: 6,
    paddingHorizontal: 14,
    marginBottom: 12,
  },
  liveBadgeDesktop: {
    paddingVertical: 10,
    paddingHorizontal: 22,
    marginBottom: 18,
  },
  liveBadgeText: {
    color: palette.danger,
    fontSize: 12,
    fontWeight: '700',
  },
  liveBadgeTextDesktop: {
    fontSize: 17,
  },
  projectorBadge: {
    alignSelf: 'center',
    backgroundColor: '#dcfce7',
    borderWidth: 1,
    borderColor: palette.primary,
    borderRadius: 999,
    paddingVertical: 10,
    paddingHorizontal: 20,
    marginBottom: 16,
  },
  projectorBadgeText: {
    fontSize: 18,
    fontWeight: '800',
    color: '#166534',
  },
  compactChartContainer: {
    width: '100%',
    backgroundColor: '#ffffff',
    borderRadius: 16,
    padding: 16,
    marginBottom: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  compactChartContainerDesktop: {
    borderRadius: 22,
    padding: 30,
    marginBottom: 0,
  },
  compactChartContainerDesktopStretch: {
    flex: 1,
    minHeight: 620,
  },
  compactChartContainerProjector: {
    minHeight: 760,
    padding: 36,
  },
  chartsRow: { flexDirection: 'row', justifyContent: 'space-around', alignItems: 'flex-end', gap: 4 },
  chartsRowDesktop: { gap: 20 },
  compactColumn: { flex: 1, alignItems: 'center', gap: 2 },
  compactColumnDesktop: { gap: 8 },
  compactBarWrapper: { height: 120, justifyContent: 'flex-end' },
  compactBarWrapperDesktop: { height: 260 },
  compactBarWrapperProjector: { height: 340 },
  compactBar: {
    width: 32,
    height: 120,
    backgroundColor: '#f3f4f6',
    borderRadius: 6,
    overflow: 'hidden',
    justifyContent: 'flex-end',
  },
  compactBarDesktop: {
    width: 72,
    height: 260,
    borderRadius: 10,
  },
  compactBarProjector: {
    width: 92,
    height: 340,
    borderRadius: 12,
  },
  compactBarFill: { width: '100%', borderRadius: 6 },
  barFillSi: { backgroundColor: palette.primary },
  barFillNo: { backgroundColor: palette.danger },
  barFillPending: { backgroundColor: '#f59e0b' },
  barFillAbsent: { backgroundColor: '#9ca3af' },
  compactBarValue: { fontSize: 14, fontWeight: '800', color: '#1f2937' },
  compactBarValueDesktop: { fontSize: 34 },
  compactBarValueProjector: { fontSize: 44 },
  compactBarPercentage: { fontSize: 10, fontWeight: '700', color: '#6b7280' },
  compactBarPercentageDesktop: { fontSize: 17 },
  compactBarPercentageProjector: { fontSize: 24 },
  compactBarEmoji: { fontSize: 16, marginVertical: 2 },
  compactBarEmojiDesktop: { fontSize: 28, marginVertical: 4 },
  compactBarEmojiProjector: { fontSize: 34, marginVertical: 8 },
  compactBarLabel: { fontSize: 9, fontWeight: '600', color: '#4b5563', textAlign: 'center', lineHeight: 12 },
  compactBarLabelDesktop: { fontSize: 16, lineHeight: 20 },
  compactBarLabelProjector: { fontSize: 21, lineHeight: 26, fontWeight: '800' },
  desktopMainGrid: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: 24,
    minHeight: 680,
  },
  desktopMainGridProjector: {
    minHeight: 840,
    gap: 30,
  },
  desktopChartColumn: {
    flex: 2,
  },
  desktopInfoColumn: {
    flex: 1,
    gap: 18,
    justifyContent: 'space-between',
  },
  summaryBoxDesktopStretch: {
    flex: 1,
    marginBottom: 0,
  },
  summaryBoxProjector: {
    padding: 30,
  },
  resultBoxDesktopStretch: {
    flex: 1,
    marginBottom: 0,
    justifyContent: 'center',
  },
  resultBoxProjector: {
    padding: 34,
  },
  summaryLabelProjector: {
    fontSize: 24,
  },
  summaryValueProjector: {
    fontSize: 40,
  },
  resultLabelProjector: {
    fontSize: 30,
  },
  resultInfoProjector: {
    fontSize: 24,
    lineHeight: 34,
  },
  resultTextProjector: {
    fontSize: 72,
  },
});
