import { StyleSheet } from 'react-native';
import { palette } from '@/src/styles/tokens';

export const styles = StyleSheet.create({
  container: { flex: 1 },
  scrollContent: {
    flexGrow: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
    paddingVertical: 40,
  },
  card: {
    width: '100%',
    maxWidth: 650,
    backgroundColor: palette.white,
    padding: 28,
    borderRadius: 20,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 5,
  },
  icon: { fontSize: 64, marginBottom: 16 },
  title: {
    fontSize: 26,
    fontWeight: '800',
    marginBottom: 20,
    textAlign: 'center',
    color: palette.textPrimary,
  },
  propuestaBox: {
    width: '100%',
    backgroundColor: '#f9fafb',
    padding: 16,
    borderRadius: 12,
    marginBottom: 20,
  },
  propuestaTitulo: { fontSize: 18, fontWeight: '700', color: palette.textPrimary, marginBottom: 8, textAlign: 'center' },
  propuestaDescripcion: { fontSize: 14, color: palette.textSecondary, textAlign: 'center', lineHeight: 20 },
  summaryBox: {
    width: '100%',
    backgroundColor: '#f0fdf4',
    padding: 16,
    borderRadius: 12,
    marginBottom: 24,
    gap: 8,
  },
  summaryRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  summaryLabel: { fontSize: 14, fontWeight: '600', color: palette.textSecondary },
  summaryValue: { fontSize: 16, fontWeight: '700', color: palette.primary },
  chartContainer: {
    width: '100%',
    backgroundColor: '#ffffff',
    borderRadius: 20,
    padding: 20,
    marginBottom: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 5,
  },
  chartTitle: { fontSize: 20, fontWeight: '800', color: palette.textPrimary, marginBottom: 16, textAlign: 'center' },
  columnsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'flex-end',
    height: 160,
    gap: 8,
    paddingHorizontal: 4,
    marginBottom: 8,
  },
  baseLine: { width: '100%', height: 3, backgroundColor: '#e5e7eb', borderRadius: 2, marginTop: -3 },
  columnWrapper: { flex: 1, alignItems: 'center', justifyContent: 'flex-end', minHeight: 240, maxWidth: 85 },
  columnBar: {
    width: '100%',
    height: 160,
    backgroundColor: '#f3f4f6',
    borderRadius: 10,
    justifyContent: 'flex-end',
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: '#e5e7eb',
  },
  columnFill: {
    width: '100%',
    borderRadius: 8,
    minHeight: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
  },
  columnFillSi: { backgroundColor: palette.primary },
  columnFillNo: { backgroundColor: palette.danger },
  columnFillPending: { backgroundColor: '#f59e0b' },
  columnFillAbsent: { backgroundColor: '#9ca3af' },
  columnStats: { marginTop: 10, alignItems: 'center', height: 40 },
  columnValue: { fontSize: 19, fontWeight: '900', color: '#1f2937' },
  columnPercentage: { fontSize: 11, fontWeight: '700', color: '#6b7280' },
  columnLabelContainer: { marginTop: 4, alignItems: 'center', height: 46, justifyContent: 'flex-start' },
  columnLabel: { fontSize: 10, fontWeight: '700', color: '#4b5563', textAlign: 'center', lineHeight: 12 },
  resultBox: {
    width: '100%',
    backgroundColor: '#f0fdf4',
    padding: 20,
    borderRadius: 12,
    marginBottom: 24,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#16a34a',
  },
  resultLabel: { fontSize: 16, fontWeight: '600', color: palette.textSecondary, marginBottom: 4 },
  resultInfo: { fontSize: 14, color: palette.textSecondary, marginBottom: 8, textAlign: 'center' },
  resultText: { fontSize: 28, fontWeight: '800', textAlign: 'center' },
  compactChartContainer: {
    width: '100%',
    backgroundColor: '#ffffff',
    borderRadius: 16,
    padding: 16,
    marginBottom: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  chartsRow: { flexDirection: 'row', justifyContent: 'space-around', alignItems: 'flex-end', gap: 4 },
  compactColumn: { flex: 1, alignItems: 'center', gap: 2 },
  compactBarWrapper: { height: 120, justifyContent: 'flex-end' },
  compactBar: {
    width: 32,
    height: 120,
    backgroundColor: '#f3f4f6',
    borderRadius: 6,
    overflow: 'hidden',
    justifyContent: 'flex-end',
  },
  compactBarFill: { width: '100%', borderRadius: 6 },
  barFillSi: { backgroundColor: palette.primary },
  barFillNo: { backgroundColor: palette.danger },
  barFillPending: { backgroundColor: '#f59e0b' },
  barFillAbsent: { backgroundColor: '#9ca3af' },
  compactBarValue: { fontSize: 14, fontWeight: '800', color: '#1f2937' },
  compactBarPercentage: { fontSize: 10, fontWeight: '700', color: '#6b7280' },
  compactBarEmoji: { fontSize: 16, marginVertical: 2 },
  compactBarLabel: { fontSize: 9, fontWeight: '600', color: '#4b5563', textAlign: 'center', lineHeight: 12 },
  backBtn: {
    width: '100%',
    backgroundColor: 'transparent',
    paddingVertical: 10,
    paddingHorizontal: 0,
    alignItems: 'center',
  },
  backBtnText: {
    color: '#065f46',
    fontWeight: '700',
    fontSize: 15,
  },
});
