import { StyleSheet } from 'react-native';
import { palette } from '@/src/styles/tokens';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  content: {
    alignItems: 'center',
    maxWidth: 400,
    width: '100%',
  },
  logoContainer: {
    marginBottom: 24,
  },
  logo: {
    width: 140,
    height: 140,
  },
  title: {
    fontSize: 26,
    fontWeight: 'bold',
    color: palette.primaryDark,
    marginBottom: 8,
    textAlign: 'center',
  },
  subtitle: {
    fontSize: 18,
    color: '#047857',
    marginBottom: 12,
    fontWeight: '600',
  },
  subtitleApoderado: {
    fontSize: 16,
    color: '#f59e0b',
    marginBottom: 20,
    fontWeight: '600',
    textAlign: 'center',
  },
  loadingContainer: {
    marginBottom: 32,
    padding: 20,
  },
  infoContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    borderRadius: 16,
    padding: 24,
    marginBottom: 24,
    width: '100%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  infoTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#065f46',
    marginBottom: 12,
    textAlign: 'center',
  },
  infoText: {
    fontSize: 15,
    color: palette.textSecondary,
    textAlign: 'center',
    lineHeight: 22,
  },
  timerContainer: {
    marginTop: 20,
    paddingTop: 20,
    borderTopWidth: 1,
    borderTopColor: '#d1d5db',
    alignItems: 'center',
  },
  timerLabel: {
    fontSize: 14,
    color: palette.textSecondary,
    marginBottom: 8,
  },
  timerValue: {
    fontSize: 32,
    fontWeight: 'bold',
    color: palette.primary,
    fontFamily: 'monospace',
  },
  quorumContainer: {
    marginTop: 20,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: '#d1d5db',
    alignItems: 'center',
  },
  quorumLabel: {
    fontSize: 14,
    color: palette.primaryDark,
    fontWeight: '700',
    marginBottom: 8,
  },
  quorumBar: {
    width: '100%',
    height: 12,
    backgroundColor: '#e5e7eb',
    borderRadius: 999,
    overflow: 'hidden',
  },
  quorumFill: {
    height: '100%',
    borderRadius: 999,
  },
  quorumFillOk: {
    backgroundColor: palette.primary,
  },
  quorumFillPending: {
    backgroundColor: '#f59e0b',
  },
  quorumHint: {
    marginTop: 8,
    fontSize: 12,
    color: '#4b5563',
    textAlign: 'center',
  },
  voteNowButton: {
    backgroundColor: palette.info,
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 12,
    alignItems: 'center',
    width: '80%',
  },
  voteNowText: {
    color: palette.white,
    fontSize: 16,
    fontWeight: '700',
  },
  statusContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.8)',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#10b981',
    marginRight: 8,
  },
  statusText: {
    fontSize: 13,
    color: palette.primaryDark,
    fontWeight: '500',
  },
  cronometroContainer: {
    alignItems: 'center',
    marginVertical: 20,
  },
  circlesRow: {
    flexDirection: 'row',
    gap: 20,
    marginBottom: 20,
  },
  circleContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  circleText: {
    position: 'absolute',
    alignItems: 'center',
  },
  circleValue: {
    fontSize: 48,
    fontWeight: 'bold',
    color: palette.primaryDark,
  },
  circleLabel: {
    fontSize: 14,
    color: '#047857',
    fontWeight: '600',
  },
  cronometroEstado: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#065f46',
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 20,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalContent: {
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 24,
    width: '90%',
    maxWidth: 400,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 8,
  },
  modalIcon: {
    fontSize: 56,
    marginBottom: 12,
  },
  modalTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#dc2626',
    marginBottom: 16,
    textAlign: 'center',
  },
  modalText: {
    fontSize: 16,
    color: '#374151',
    textAlign: 'center',
    lineHeight: 24,
    marginBottom: 12,
  },
  modalTextWarning: {
    fontSize: 15,
    color: '#065f46',
    fontWeight: '600',
    textAlign: 'center',
    marginTop: 8,
    marginBottom: 12,
  },
  warningList: {
    alignSelf: 'stretch',
    backgroundColor: '#fef3c7',
    padding: 16,
    borderRadius: 12,
    marginBottom: 20,
  },
  warningItem: {
    fontSize: 14,
    color: '#92400e',
    lineHeight: 22,
    marginBottom: 8,
  },
  modalButton: {
    backgroundColor: palette.primary,
    paddingVertical: 14,
    paddingHorizontal: 32,
    borderRadius: 12,
    minWidth: 150,
    alignItems: 'center',
  },
  modalButtonText: {
    color: palette.white,
    fontSize: 16,
    fontWeight: 'bold',
  },
});
