import { StyleSheet } from 'react-native';
import { palette } from '@/src/styles/tokens';

export const styles = StyleSheet.create({
  container: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 16 },
  card: {
    width: '100%',
    maxWidth: 600,
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    padding: 36,
    borderRadius: 24,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.25,
    shadowRadius: 16,
    elevation: 10,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  iconContainer: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: 'rgba(22, 163, 74, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
  },
  ballotIcon: {
    fontSize: 48,
  },
  title: {
    fontSize: 28,
    fontWeight: '800',
    marginBottom: 16,
    textAlign: 'center',
    color: palette.textPrimary,
    letterSpacing: -0.5,
  },
  subtitle: { fontSize: 16, color: palette.textSecondary, marginBottom: 16, textAlign: 'center' },
  description: {
    fontSize: 17,
    color: '#4b5563',
    marginBottom: 32,
    textAlign: 'center',
    lineHeight: 26,
  },
  waitingIcon: {
    fontSize: 64,
    marginBottom: 16,
  },
  waitingMessage: {
    fontSize: 18,
    fontWeight: '700',
    color: palette.textPrimary,
    textAlign: 'center',
    marginBottom: 8,
  },
  waitingSubtext: {
    fontSize: 14,
    color: palette.textSecondary,
    textAlign: 'center',
    marginBottom: 24,
  },
  votePrompt: {
    fontSize: 20,
    fontWeight: '700',
    color: palette.textPrimary,
    textAlign: 'center',
    marginBottom: 24,
    letterSpacing: -0.5,
  },
  buttonsRow: {
    flexDirection: 'row',
    gap: 20,
    width: '100%',
  },
  voteBtn: {
    flex: 1,
    paddingVertical: 24,
    paddingHorizontal: 16,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 8,
    elevation: 6,
    minHeight: 120,
  },
  yesBtn: {
    backgroundColor: palette.primary,
    shadowColor: '#16a34a',
  },
  noBtn: {
    backgroundColor: palette.danger,
    shadowColor: '#ef4444',
  },
  voteBtnIcon: {
    fontSize: 40,
    marginBottom: 8,
  },
  voteBtnText: {
    color: palette.white,
    fontSize: 22,
    fontWeight: '800',
    letterSpacing: 1,
  },
  thanksContainer: {
    alignItems: 'center',
    paddingVertical: 24,
  },
  checkCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: palette.primary,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
    shadowColor: palette.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  checkIcon: {
    color: palette.white,
    fontSize: 48,
    fontWeight: '900',
  },
  thanks: {
    fontSize: 24,
    color: palette.primary,
    fontWeight: '800',
    textAlign: 'center',
    marginBottom: 12,
    letterSpacing: -0.5,
  },
  thanksSubtext: {
    fontSize: 16,
    color: '#4b5563',
    textAlign: 'center',
    marginBottom: 8,
    fontWeight: '600',
  },
  thanksNote: {
    fontSize: 14,
    color: palette.textSecondary,
    textAlign: 'center',
    fontStyle: 'italic',
  },
  backBtn: {
    marginTop: 16,
    backgroundColor: '#f3f4f6',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#e5e7eb',
  },
  backBtnText: { color: '#374151', fontWeight: '600' },
});
